package org.jcs.egm.stones.stone_reality;

import net.minecraft.resources.ResourceLocation;
import org.jcs.egm.config.ModCommonConfig;

import java.util.HashSet;
import java.util.Set;

public class WilledChaosBlacklistHelper {
    private static final Set<String> HARDCODED_BLOCK_IDS = Set.of(
            "minecraft:acacia_button",
            "minecraft:acacia_door",
            "minecraft:acacia_pressure_plate",
            "minecraft:acacia_sapling",
            "minecraft:allium",
            "minecraft:azalea",
            "minecraft:bamboo",
            "minecraft:bamboo_button",
            "minecraft:bamboo_door",
            "minecraft:bamboo_pressure_plate",
            "minecraft:barrier",
            "minecraft:beetroots",
            "minecraft:birch_button",
            "minecraft:birch_door",
            "minecraft:birch_pressure_plate",
            "minecraft:birch_sapling",
            "minecraft:black_banner",
            "minecraft:black_bed",
            "minecraft:blue_banner",
            "minecraft:blue_bed",
            "minecraft:blue_orchid",
            "minecraft:brain_coral",
            "minecraft:brain_coral_fan",
            "minecraft:brain_coral_wall_fan",
            "minecraft:brown_banner",
            "minecraft:brown_bed",
            "minecraft:brown_mushroom",
            "minecraft:bubble_coral",
            "minecraft:bubble_coral_fan",
            "minecraft:bubble_coral_wall_fan",
            "minecraft:cactus",
            "minecraft:carrots",
            "minecraft:chain_command_block",
            "minecraft:chorus_flower",
            "minecraft:chorus_plant",
            "minecraft:cocoa",
            "minecraft:comparator",
            "minecraft:cornflower",
            "minecraft:crimson_button",
            "minecraft:crimson_door",
            "minecraft:crimson_fungus",
            "minecraft:crimson_pressure_plate",
            "minecraft:crimson_roots",
            "minecraft:cyan_banner",
            "minecraft:cyan_bed",
            "minecraft:dandelion",
            "minecraft:dark_oak_button",
            "minecraft:dark_oak_door",
            "minecraft:dark_oak_pressure_plate",
            "minecraft:daylight_detector",
            "minecraft:dead_brain_coral",
            "minecraft:dead_brain_coral_fan",
            "minecraft:dead_brain_coral_wall_fan",
            "minecraft:dead_bubble_coral",
            "minecraft:dead_bubble_coral_fan",
            "minecraft:dead_bubble_coral_wall_fan",
            "minecraft:dead_bush",
            "minecraft:dead_fire_coral",
            "minecraft:dead_fire_coral_fan",
            "minecraft:dead_fire_coral_wall_fan",
            "minecraft:dead_horn_coral",
            "minecraft:dead_horn_coral_fan",
            "minecraft:dead_horn_coral_wall_fan",
            "minecraft:dead_tube_coral",
            "minecraft:dead_tube_coral_fan",
            "minecraft:dead_tube_coral_wall_fan",
            "minecraft:dispenser",
            "minecraft:dropper",
            "minecraft:end_gateway",
            "minecraft:end_portal",
            "minecraft:end_portal_frame",
            "minecraft:fern",
            "minecraft:fire",
            "minecraft:flowering_azalea",
            "minecraft:glow_lichen",
            "minecraft:grass",
            "minecraft:gray_banner",
            "minecraft:gray_bed",
            "minecraft:green_banner",
            "minecraft:green_bed",
            "minecraft:heavy_weighted_pressure_plate",
            "minecraft:horn_coral",
            "minecraft:horn_coral_fan",
            "minecraft:horn_coral_wall_fan",
            "minecraft:jungle_button",
            "minecraft:jungle_door",
            "minecraft:jungle_pressure_plate",
            "minecraft:kelp",
            "minecraft:kelp_plant",
            "minecraft:large_fern",
            "minecraft:lava",
            "minecraft:lever",
            "minecraft:light_blue_banner",
            "minecraft:light_blue_bed",
            "minecraft:light_gray_banner",
            "minecraft:light_gray_bed",
            "minecraft:light_weighted_pressure_plate",
            "minecraft:lily_pad",
            "minecraft:lime_banner",
            "minecraft:lime_bed",
            "minecraft:magenta_banner",
            "minecraft:magenta_bed",
            "minecraft:mangrove_button",
            "minecraft:mangrove_door",
            "minecraft:mangrove_pressure_plate",
            "minecraft:mangrove_propagule",
            "minecraft:mangrove_roots",
            "minecraft:melon_stem",
            "minecraft:nether_portal",
            "minecraft:note_block",
            "minecraft:oak_button",
            "minecraft:oak_door",
            "minecraft:oak_pressure_plate",
            "minecraft:oak_sapling",
            "minecraft:observer",
            "minecraft:orange_banner",
            "minecraft:orange_bed",
            "minecraft:orange_tulip",
            "minecraft:oxeye_daisy",
            "minecraft:peony",
            "minecraft:pink_banner",
            "minecraft:pink_bed",
            "minecraft:pink_tulip",
            "minecraft:piston",
            "minecraft:piston_head",
            "minecraft:poppy",
            "minecraft:potatoes",
            "minecraft:pumpkin_stem",
            "minecraft:purple_banner",
            "minecraft:purple_bed",
            "minecraft:purple_tulip",
            "minecraft:red_banner",
            "minecraft:red_bed",
            "minecraft:red_mushroom",
            "minecraft:red_tulip",
            "minecraft:redstone_torch",
            "minecraft:redstone_wall_torch",
            "minecraft:redstone_wire",
            "minecraft:repeater",
            "minecraft:repeating_command_block",
            "minecraft:rose_bush",
            "minecraft:sculk_sensor",
            "minecraft:sculk_shrieker",
            "minecraft:sea_pickle",
            "minecraft:soul_fire",
            "minecraft:spruce_button",
            "minecraft:spruce_door",
            "minecraft:spruce_pressure_plate",
            "minecraft:sticky_piston",
            "minecraft:stone_button",
            "minecraft:stone_pressure_plate",
            "minecraft:structure_void",
            "minecraft:sugar_cane",
            "minecraft:sunflower",
            "minecraft:sweet_berry_bush",
            "minecraft:tall_grass",
            "minecraft:tall_seagrass",
            "minecraft:target",
            "minecraft:tnt",
            "minecraft:torchflower",
            "minecraft:torchflower_crop",
            "minecraft:tripwire",
            "minecraft:tripwire_hook",
            "minecraft:tube_coral",
            "minecraft:tube_coral_fan",
            "minecraft:tube_coral_wall_fan",
            "minecraft:twisting_vines",
            "minecraft:twisting_vines_plant",
            "minecraft:vines",
            "minecraft:warped_button",
            "minecraft:warped_door",
            "minecraft:warped_fungus",
            "minecraft:warped_pressure_plate",
            "minecraft:warped_roots",
            "minecraft:water",
            "minecraft:weeping_vines",
            "minecraft:weeping_vines_plant",
            "minecraft:wheat",
            "minecraft:white_banner",
            "minecraft:white_bed",
            "minecraft:white_tulip",
            "minecraft:yellow_banner",
            "minecraft:yellow_bed",
            // big boy bans
            "minecraft:jigsaw",
            "minecraft:bedrock"
    );

    public static boolean isHardcodedBlacklisted(ResourceLocation id) {
        return id != null && HARDCODED_BLOCK_IDS.contains(id.toString());
    }

    public static boolean isConfigBlacklisted(ResourceLocation id) {
        if (id == null) return false;
        Set<String> configBlacklist = new HashSet<>(ModCommonConfig.REALITY_STONE_BLOCK_BLACKLIST.get());
        return configBlacklist.contains(id.toString());
    }

    private static final Set<String> HARDCODED_MOB_IDS = Set.of(
            "minecraft:ender_dragon",
            "minecraft:wither"
    );

    public static boolean isHardcodedEntityBlacklisted(ResourceLocation id) {
        return id != null && HARDCODED_MOB_IDS.contains(id.toString());
    }

    public static boolean isConfigEntityBlacklisted(ResourceLocation id) {
        if (id == null) return false;
        Set<String> configEntityBlacklist = new HashSet<>(ModCommonConfig.REALITY_STONE_ENTITY_BLACKLIST.get());
        return configEntityBlacklist.contains(id.toString());
    }
}

